# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_details',
            name='avatar',
        ),
    ]
