# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180605_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_details',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='https://api.cloudinary.com/v1_1/domkcrvzu/upload'),
        ),
    ]
