# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 11:54
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180605_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_details',
            name='Gender',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='users_details',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
