# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180605_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_details',
            name='Gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
