# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_login_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_details',
            name='country',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='users_details',
            name='info',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
