# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_users_details_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_details',
            name='otp',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
